#include "IndirectStructs.hlsl"

#pragma kernel CSMain
// #pragma enable_d3d11_debug_symbols

#define THREAD_GROUP_SIZE_X 64
#define THREAD_GROUP_SIZE_Y 1
#define THREAD_GROUP_SIZE_Z 1

#define VEGDATA_NUM 3

StructuredBuffer<float3> _Position;
StructuredBuffer<float3> _Rotation;
StructuredBuffer<float> _Scale;
StructuredBuffer<SortingData> _SortingData;

RWStructuredBuffer<float4x4> _LocalToWorldMatrixsBuffer;

float4 EncodeFloatRGBAFloat(float4 v)
{
    uint4 i = asuint(v);
    float4 val = (i & 0xFFFFFFFF) / 4294967295.0;
    return val;
}

float4 DecodeFloatRGBAFloat(float4 rgba)
{
    uint4 value = uint4(rgba * 4294967295.0);
    return asfloat(value);
}

float4x4 rotationMatrix(float3 axis, float angle)
{
    axis = normalize(axis);
    float s = sin(angle);
    float c = cos(angle);
    float oc = 1.0 - c;

    return float4x4(
        oc * axis.x * axis.x + c, oc * axis.x * axis.y - axis.z * s, oc * axis.z * axis.x + axis.y * s, 0.0,
        oc * axis.x * axis.y + axis.z * s, oc * axis.y * axis.y + c, oc * axis.y * axis.z - axis.x * s, 0.0,
        oc * axis.z * axis.x - axis.y * s, oc * axis.y * axis.z + axis.x * s, oc * axis.z * axis.z + c, 0.0,
        0, 0, 0,          1.0);
}

[numthreads(THREAD_GROUP_SIZE_X,THREAD_GROUP_SIZE_Y,THREAD_GROUP_SIZE_Z)]
void CSMain (uint3 _dispatchThreadID : SV_DispatchThreadID)
{
    uint tID = _dispatchThreadID.x;

    float3 position = _Position[tID];
    float3 rotation = _Rotation[tID];
    float3 scale = float3(1,1,1) * _Scale[tID];

    float4x4 xRotationMatrix = rotationMatrix(float3(1, 0, 0), radians(rotation.x));
    float4x4 yRotationMatrix = rotationMatrix(float3(0, 1, 0), radians(rotation.y));
    float4x4 zRotationMatrix = rotationMatrix(float3(0, 0, 1), radians(rotation.z));
    float4x4 rotMatrix = mul(yRotationMatrix, mul(zRotationMatrix, xRotationMatrix));

    float4x4 translation = {
        scale.x, 0, 0, position.x,
        0, scale.y, 0, position.y,
        0, 0, scale.z, position.z,
        0, 0, 0, 1
    };

    float4x4 objectToWorld = mul(translation, rotMatrix);
    _LocalToWorldMatrixsBuffer[tID] = objectToWorld;
}
