#pragma kernel CSMain
// #pragma enable_d3d11_debug_symbols

#define THREAD_GROUP_SIZE_X 128
#define THREAD_GROUP_SIZE_Y 1
#define THREAD_GROUP_SIZE_Z 1

cbuffer CB
{
    groupshared uint temp[2 * THREAD_GROUP_SIZE_X];
}

StructuredBuffer<uint> _IsVisibleBuffer;
RWStructuredBuffer<uint> _GroupSumArray;
RWStructuredBuffer<uint> _ScannedInstanceVisibleBuffer;

[numthreads(THREAD_GROUP_SIZE_X,THREAD_GROUP_SIZE_Y,THREAD_GROUP_SIZE_Z)]
void CSMain (
        in uint3 _dispatchThreadID : SV_DispatchThreadID,
        in uint  _groupIndex       : SV_GroupIndex,
        in uint3 _groupID          : SV_GroupID,
        in uint3 _groupThreadID    : SV_GroupThreadID
    )
{
    int tID = (int) _dispatchThreadID.x;
    int groupTID = (int) _groupThreadID.x;

    int offset = 1;
    temp[2 * groupTID] = _IsVisibleBuffer[2 * tID];
    temp[2 * groupTID + 1] = _IsVisibleBuffer[2 * tID + 1];
    int d;
    const int NoofElements = 2 * THREAD_GROUP_SIZE_X;

    //reduction
    for (d = NoofElements >> 1; d > 0; d >>= 1)
    {
        GroupMemoryBarrierWithGroupSync();

        if (groupTID < d)
        {
            int ai = offset * (2 * groupTID + 1) - 1;
            int bi = offset * (2 * groupTID + 2) - 1;
            temp[bi] += temp[ai];
        }
        offset *= 2;
    }

    if (groupTID == 0)
    {
        _GroupSumArray[_groupID.x] = temp[NoofElements - 1];
        temp[NoofElements - 1] = 0;
    }

    //prefix sum
    for (d = 1; d < NoofElements; d *= 2)
    {
        offset >>= 1;

        GroupMemoryBarrierWithGroupSync();

        if (groupTID < d)
        {
            int ai = offset * (2 * groupTID + 1) - 1;
            int bi = offset * (2 * groupTID + 2) - 1;
            int t = temp[ai];
            temp[ai] = temp[bi];
            temp[bi] += t;
        }
    }

    GroupMemoryBarrierWithGroupSync();

    _ScannedInstanceVisibleBuffer[2 * tID] = temp[2 * groupTID];
    _ScannedInstanceVisibleBuffer[2 * tID + 1] = temp[2 * groupTID + 1];
}
// 0 1 2 3 4 5 6 7
//   1   5   9   13
//       6       22
//               28
//0 1 2 6 4 9 6 28

//0 1 2 6 4 9 6 0
//0 1 2 0 4 9 6 6
//0 0 2 1 4 6 6 15
//0 0 1 3 6 10 15 21